export const STATE_DATA: Record<string, { olympic: number; para: number; sports: { name: string; count: number }[] }> = {
  "California": { olympic: 342, para: 156, sports: [{name: "Swimming", count: 82}, {name: "Track & Field", count: 64}, {name: "Water Polo", count: 45}, {name: "Volleyball", count: 32}, {name: "Gymnastics", count: 28}] },
  "Texas": { olympic: 218, para: 92, sports: [{name: "Track & Field", count: 58}, {name: "Swimming", count: 42}, {name: "Basketball", count: 31}, {name: "Diving", count: 22}, {name: "Gymnastics", count: 18}] },
  "Florida": { olympic: 184, para: 76, sports: [{name: "Swimming", count: 45}, {name: "Tennis", count: 28}, {name: "Track & Field", count: 26}, {name: "Golf", count: 18}, {name: "Sailing", count: 12}] },
  "New York": { olympic: 165, para: 84, sports: [{name: "Fencing", count: 38}, {name: "Rowing", count: 24}, {name: "Wrestling", count: 22}, {name: "Basketball", count: 18}, {name: "Equestrian", count: 15}] },
  "Pennsylvania": { olympic: 142, para: 58, sports: [{name: "Wrestling", count: 34}, {name: "Track & Field", count: 28}, {name: "Swimming", count: 22}, {name: "Field Hockey", count: 18}, {name: "Rowing", count: 14}] },
  "Ohio": { olympic: 128, para: 45, sports: [{name: "Gymnastics", count: 28}, {name: "Track & Field", count: 24}, {name: "Swimming", count: 20}, {name: "Boxing", count: 15}, {name: "Synchronized Swimming", count: 12}] },
  "Illinois": { olympic: 115, para: 52, sports: [{name: "Basketball", count: 26}, {name: "Track & Field", count: 22}, {name: "Swimming", count: 18}, {name: "Fencing", count: 12}, {name: "Volleyball", count: 10}] },
  "Colorado": { olympic: 98, para: 64, sports: [{name: "Skiing", count: 35}, {name: "Snowboarding", count: 28}, {name: "Cycling", count: 15}, {name: "Triathlon", count: 10}, {name: "Shooting", count: 8}] },
  "Washington": { olympic: 88, para: 38, sports: [{name: "Rowing", count: 24}, {name: "Sailing", count: 18}, {name: "Track & Field", count: 15}, {name: "Cycling", count: 12}, {name: "Soccer", count: 10}] },
  "Massachusetts": { olympic: 92, para: 34, sports: [{name: "Sailing", count: 22}, {name: "Rowing", count: 18}, {name: "Ice Hockey", count: 15}, {name: "Fencing", count: 12}, {name: "Swimming", count: 10}] },
  "Alabama": { olympic: 45, para: 12, sports: [{name: "Track & Field", count: 15}, {name: "Basketball", count: 10}, {name: "Softball", count: 8}, {name: "Swimming", count: 6}, {name: "Boxing", count: 4}] },
  "Arizona": { olympic: 52, para: 18, sports: [{name: "Swimming", count: 18}, {name: "Golf", count: 12}, {name: "Baseball", count: 10}, {name: "Softball", count: 8}, {name: "Archery", count: 4}] },
  "Arkansas": { olympic: 18, para: 6, sports: [{name: "Track & Field", count: 10}, {name: "Basketball", count: 4}, {name: "Baseball", count: 2}, {name: "Golf", count: 2}] },
  "California (Central)": { olympic: 45, para: 12, sports: [{name: "Track & Field", count: 15}, {name: "Wrestling", count: 10}] },
  "Georgia": { olympic: 86, para: 32, sports: [{name: "Basketball", count: 24}, {name: "Track & Field", count: 22}, {name: "Gymnastics", count: 14}] },
  "Hawaii": { olympic: 38, para: 12, sports: [{name: "Surfing", count: 15}, {name: "Swimming", count: 12}, {name: "Volleyball", count: 11}] },
  "Michigan": { olympic: 112, para: 42, sports: [{name: "Ice Hockey", count: 32}, {name: "Swimming", count: 24}, {name: "Track & Field", count: 20}] },
  "New Jersey": { olympic: 98, para: 38, sports: [{name: "Fencing", count: 22}, {name: "Track & Field", count: 18}, {name: "Equestrian", count: 15}] },
  "North Carolina": { olympic: 74, para: 28, sports: [{name: "Basketball", count: 22}, {name: "Swimming", count: 18}, {name: "Track & Field", count: 14}] },
  "Oregon": { olympic: 68, para: 24, sports: [{name: "Track & Field", count: 32}, {name: "Cycling", count: 12}, {name: "Rowing", count: 10}] },
  "Virginia": { olympic: 82, para: 30, sports: [{name: "Swimming", count: 24}, {name: "Track & Field", count: 20}, {name: "Equestrian", count: 18}] },
  "Wyoming": { olympic: 8, para: 3, sports: [{name: "Shooting", count: 4}, {name: "Wrestling", count: 2}, {name: "Track & Field", count: 2}] },
};
